export const notes = [
  {
    id: 'n101',
    createdAt: 1112222,
    type: 'NoteTxt',
    isPinned: true,
    style: { backgroundColor: '#e7ffd3' },
    info: { txt: 'Fullstack Me Baby!' },
  },
  {
    id: 'n102',
    createdAt: 1112223,
    type: 'NoteImg',
    isPinned: false,
    style: { backgroundColor: '#f5faff' },
    info: { url: 'https://picsum.photos/200/300', title: 'Bobi and Me' },
  },
  {
    id: 'n103',
    createdAt: 1112224,
    type: 'NoteTodos',
    isPinned: false,
    style: { backgroundColor: '#f8d3ff' },
    info: {
      title: 'Get my stuff together',
      todos: [
        { txt: 'Driving license', isDone: true },
        { txt: 'Coding power', isDone: false },
      ],
    },
  },
  {
    id: 'n104',
    createdAt: 1112225,
    type: 'NoteTxt',
    isPinned: true,
    style: { backgroundColor: '#fff5d3' },
    info: { txt: 'Remember to call mom on Friday' },
  },
  {
    id: 'n105',
    createdAt: 1112226,
    type: 'NoteImg',
    isPinned: false,
    style: { backgroundColor: '#ffe8e8' },
    info: {
      url: 'https://picsum.photos/id/1015/200/300',
      title: 'Trip to the mountains',
    },
  },
  {
    id: 'n106',
    createdAt: 1112227,
    type: 'NoteTodos',
    isPinned: false,
    style: { backgroundColor: '#d3f0ff' },
    info: {
      title: 'Shopping list',
      todos: [
        { txt: 'Milk', isDone: false },
        { txt: 'Bread', isDone: true },
        { txt: 'Coffee', isDone: false },
        { txt: 'Eggs', isDone: false },
      ],
    },
  },
  {
    id: 'n107',
    createdAt: 1112228,
    type: 'NoteTxt',
    isPinned: false,
    style: { backgroundColor: '#f0e7ff' },
    info: { txt: 'Ideas for sprint 4: dark mode, drag & drop notes, labels' },
  },
  {
    id: 'n108',
    createdAt: 1112229,
    type: 'NoteImg',
    isPinned: false,
    style: { backgroundColor: '#e7fff9' },
    info: { url: 'https://picsum.photos/id/1025/200/300', title: 'Good boy' },
  },
  {
    id: 'n109',
    createdAt: 1112230,
    type: 'NoteTodos',
    isPinned: true,
    style: { backgroundColor: '#ffeede' },
    info: {
      title: 'Project tasks',
      todos: [
        { txt: 'Finish NoteCard cmp', isDone: true },
        { txt: 'Add edit modal', isDone: false },
        { txt: 'Filter by type', isDone: false },
      ],
    },
  },
  {
    id: 'n110',
    createdAt: 1112231,
    type: 'NoteTxt',
    isPinned: false,
    style: { backgroundColor: '#ffe7f2' },
    info: { txt: 'לא לשכוח להגיש את הספרינט עד יום חמישי!' },
  },
  {
    id: 'n111',
    createdAt: 1112232,
    type: 'NoteTodos',
    isPinned: false,
    style: { backgroundColor: '#eaffd3' },
    info: {
      title: 'Workout plan',
      todos: [
        { txt: 'Monday - Chest', isDone: true },
        { txt: 'Wednesday - Back', isDone: false },
        { txt: 'Friday - Legs', isDone: false },
      ],
    },
  },
  {
    id: 'n112',
    createdAt: 1112233,
    type: 'NoteImg',
    isPinned: false,
    style: { backgroundColor: '#f5f5f5' },
    info: {
      url: 'https://picsum.photos/id/1040/200/300',
      title: 'Dream house',
    },
  },
]
