const DAY = 1000 * 60 * 60 * 24
const now = Date.now()

// A mail belongs to the inbox when it was sent TO the loggedinUser,
// and to the sent folder when it was sent BY them (from === user email)
export const demoEmails = [
    {
        id: 'e101',
        createdAt: 1551133930500,
        subject: 'Miss you!',
        body: 'Would love to catch up sometimes',
        isRead: false,
        isStared: false,
        sentAt: 1551133930594,
        removedAt: null,
        from: 'momo@momo.com',
        to: 'user@appsus.com',
        labels: ['romantic'],
    },
    {
        id: 'e102',
        createdAt: now - DAY * 0.2,
        subject: 'Your order #4432 is on its way',
        body: 'Hi Mahatma, your package left our warehouse and should arrive within 2 business days. Track it any time from your account page.',
        isRead: false,
        isStared: true,
        sentAt: now - DAY * 0.2,
        removedAt: null,
        from: 'no-reply@shopit.com',
        to: 'user@appsus.com',
        labels: ['important'],
    },
    {
        id: 'e103',
        createdAt: now - DAY * 1.1,
        subject: 'Sprint 3 - code review',
        body: 'Hey, I went over the mail service. The filterBy looks good, just make sure the trash folder shows removed mails from both inbox and sent.',
        isRead: true,
        isStared: false,
        sentAt: now - DAY * 1.1,
        removedAt: null,
        from: 'ofek@appsus.com',
        to: 'user@appsus.com',
        labels: ['work', 'important'],
    },
    {
        id: 'e104',
        createdAt: now - DAY * 2.5,
        subject: 'Lunch tomorrow?',
        body: 'There is a new place near the office, they say the shakshuka is unreal. 13:00 works for me.',
        isRead: true,
        isStared: true,
        sentAt: now - DAY * 2.5,
        removedAt: null,
        from: 'puki@baba.com',
        to: 'user@appsus.com',
        labels: ['friends'],
    },
    {
        id: 'e105',
        createdAt: now - DAY * 4,
        subject: 'You have won a brand new car!!!',
        body: 'Congratulations! Just send us your credit card details to claim your prize.',
        isRead: false,
        isStared: false,
        sentAt: now - DAY * 4,
        removedAt: null,
        from: 'winner@totally-not-a-scam.com',
        to: 'user@appsus.com',
        labels: ['spam'],
    },
    {
        id: 'e106',
        createdAt: now - DAY * 6,
        subject: 'Monthly team meeting',
        body: 'Reminder: our monthly sync is on Sunday at 10:00. Please come with your status updates.',
        isRead: true,
        isStared: false,
        sentAt: now - DAY * 6,
        removedAt: null,
        from: 'hr@appsus.com',
        to: 'user@appsus.com',
        labels: ['work'],
    },
    // Sent mails
    {
        id: 'e107',
        createdAt: now - DAY * 1,
        subject: 'RE: Sprint 3 - code review',
        body: 'Thanks! Fixed the trash folder, it now shows every mail with a removedAt, no matter who sent it.',
        isRead: true,
        isStared: false,
        sentAt: now - DAY * 1,
        removedAt: null,
        from: 'user@appsus.com',
        to: 'ofek@appsus.com',
        labels: ['work'],
    },
    {
        id: 'e108',
        createdAt: now - DAY * 3,
        subject: 'Miss you too',
        body: 'Of course! Coffee this weekend?',
        isRead: true,
        isStared: true,
        sentAt: now - DAY * 3,
        removedAt: null,
        from: 'user@appsus.com',
        to: 'momo@momo.com',
        labels: ['romantic'],
    },
    // Drafts - created but never sent
    {
        id: 'e109',
        createdAt: now - DAY * 0.5,
        subject: 'Vacation request',
        body: 'Hi, I would like to take the last week of the month off',
        isRead: true,
        isStared: false,
        sentAt: null,
        removedAt: null,
        from: 'user@appsus.com',
        to: 'hr@appsus.com',
        labels: [],
    },
    {
        id: 'e110',
        createdAt: now - DAY * 8,
        subject: '',
        body: 'remember to send the invoice',
        isRead: true,
        isStared: false,
        sentAt: null,
        removedAt: null,
        from: 'user@appsus.com',
        to: '',
        labels: [],
    },
    // Removed mails - the trash folder
    {
        id: 'e111',
        createdAt: now - DAY * 5,
        subject: 'Newsletter - August edition',
        body: 'All the news you did not ask for, delivered straight to your inbox.',
        isRead: true,
        isStared: false,
        sentAt: now - DAY * 5,
        removedAt: now - DAY * 2,
        from: 'news@daily.com',
        to: 'user@appsus.com',
        labels: ['spam'],
    },
    {
        id: 'e112',
        createdAt: now - DAY * 9,
        subject: 'Old meeting notes',
        body: 'Attaching the notes from our last meeting, mostly irrelevant by now.',
        isRead: true,
        isStared: false,
        sentAt: now - DAY * 9,
        removedAt: now - DAY * 7,
        from: 'user@appsus.com',
        to: 'ofek@appsus.com',
        labels: ['work'],
    },
]
